# Generated by Django 6.1.1 on 2026-09-07 11:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(db_index=True, max_length=255)),
                ('initial_explanation', models.TextField()),
                ('confidence', models.IntegerField(help_text='Self-assessed confidence score (0-100)')),
                ('initial_score', models.IntegerField(blank=True, help_text='Initial understanding score (0-100)', null=True)),
                ('final_score', models.IntegerField(help_text='Final synthesized understanding score (0-100)')),
                ('verdict', models.CharField(help_text='Conceptual classification / understanding level', max_length=150)),
                ('summary', models.TextField(help_text='Executive diagnostic summary / verdict')),
                ('core_accuracy', models.IntegerField(default=0)),
                ('causal_depth', models.IntegerField(default=0)),
                ('relational_coherence', models.IntegerField(default=0)),
                ('diagnostic_dimensions', models.JSONField(blank=True, default=dict)),
                ('demonstrated_concepts', models.JSONField(blank=True, default=list)),
                ('missing_concepts', models.JSONField(blank=True, default=list)),
                ('possible_misconceptions', models.JSONField(blank=True, default=list)),
                ('confidence_calibration', models.JSONField(blank=True, default=dict)),
                ('probe_question', models.TextField(blank=True, default='')),
                ('probe_reason', models.TextField(blank=True, default='')),
                ('probe_answer', models.TextField(blank=True, default='')),
                ('diagnostic_journey', models.JSONField(blank=True, default=dict)),
                ('full_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Diagnostic Record',
                'verbose_name_plural': 'Diagnostic Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
